// all images are from unsplash legal source of free image
export const words: Record<string, { pl: string; port: string; img?: string }> =
  {
    boy: {
      pl: 'chłopiec',
      port: 'um menino',
      img: 'https://unsplash.com/photos/4LunKr1gTd8',
    },
    girl: {
      pl: 'dziewczyna',
      port: 'uma menina',
      img: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=986&q=80',
    },
    cat: {
      pl: 'kot',
      port: 'um gato',
      img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2043&q=80',
    },
    dog: {
      pl: 'pies',
      port: 'um cão',
      img: 'https://images.unsplash.com/photo-1517423568366-8b83523034fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1035&q=80',
    },
    house: {
      pl: 'dom',
      port: 'uma casa',
      img: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1065&q=80',
    },
    car: {
      pl: 'samochód',
      port: 'um carro',
      img: 'https://images.unsplash.com/photo-1602265075744-6357d01db358?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    hello: {
      pl: 'cześć',
      port: 'olá',
      img: 'https://images.unsplash.com/photo-1595013008294-506e8f306d3c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    goodbye: {
      pl: 'do widzenia',
      port: 'adeus',
      img: 'https://images.unsplash.com/photo-1595521488367-9b130f86bbe3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YnllfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
    },
    'thank you': {
      pl: 'dziękuję',
      port: 'obrigado',
      img: 'https://plus.unsplash.com/premium_photo-1677745834467-65d70311cd07?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80',
    },
    please: {
      pl: 'proszę',
      port: 'por favor',
      img: 'https://images.unsplash.com/photo-1624564890916-2669288b9f16?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    water: {
      pl: 'uma woda',
      port: 'água',
      img: 'https://images.unsplash.com/photo-1554135392-28d77d7e8202?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1480&q=80',
    },
    food: {
      pl: 'uma jedzenie',
      port: 'comida',
      img: 'https://images.unsplash.com/photo-1496412705862-e0088f16f791?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    sun: {
      pl: 'słońce',
      port: 'um sol',
      img: 'https://images.unsplash.com/photo-1604697976327-4f28ff459803?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80',
    },
    moon: {
      pl: 'księżyc',
      port: 'uma lua',
      img: 'https://images.unsplash.com/photo-1479090793912-eb9929f4fdb2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1568&q=80',
    },
    time: {
      pl: 'czas',
      port: 'o tempo',
      img: 'https://images.unsplash.com/photo-1447015237013-0e80b2786ddc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    day: {
      pl: 'dzień',
      port: 'um dia',
      img: 'https://images.unsplash.com/photo-1598992048970-fa53d75547f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    night: {
      pl: 'noc',
      port: 'uma noite',
      img: 'https://images.unsplash.com/photo-1488866022504-f2584929ca5f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2324&q=80',
    },
    tree: {
      pl: 'drzewo',
      port: 'uma árvore',
      img: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    flower: {
      pl: 'kwiat',
      port: 'uma flor',
      img: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=986&q=80',
    },
    bird: {
      pl: 'ptak',
      port: 'um pássaro',
      img: 'https://images.unsplash.com/photo-1539664030485-a936c7d29c6e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1480&q=80',
    },
    fish: {
      pl: 'ryba',
      port: 'um peixe',
      img: 'https://images.unsplash.com/photo-1522720833375-9c27ffb02a5e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2098&q=80',
    },
    book: {
      pl: 'książka',
      port: 'um livro',
      img: 'https://images.unsplash.com/photo-1589998059171-988d887df646?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2352&q=80',
    },
    pen: {
      pl: 'długopis',
      port: 'uma caneta',
      img: 'https://images.unsplash.com/photo-1585997631913-896180ae8acb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    school: {
      pl: 'szkoła',
      port: 'uma escola',
      img: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    teacher: {
      pl: 'nauczyciel',
      port: 'um professor',
      img: 'https://images.unsplash.com/photo-1597570889212-97f48e632dad?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2352&q=80',
    },
    student: {
      pl: 'uczeń',
      port: 'um aluno',
      img: 'https://images.unsplash.com/photo-1618355776464-8666794d2520?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80',
    },
    friend: {
      pl: 'przyjaciel',
      port: 'um amigo',
      img: 'https://images.unsplash.com/photo-1530047139082-5435ca3c4614?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    family: {
      pl: 'rodzina',
      port: 'uma família',
      img: 'https://images.unsplash.com/photo-1611516818236-8faa056fb659?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    love: {
      pl: 'miłość',
      port: 'um amor',
      img: 'https://images.unsplash.com/photo-1513279922550-250c2129b13a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    happy: {
      pl: 'szczęśliwy',
      port: 'feliz',
      img: 'https://plus.unsplash.com/premium_photo-1664441073640-f6d692eecb26?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    },
    sad: {
      pl: 'smutny',
      port: 'triste',
      img: 'https://images.unsplash.com/photo-1597176116047-876a32798fcc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1674&q=80',
    },
    big: {
      pl: 'duży',
      port: 'grande',
      img: 'https://images.unsplash.com/photo-1513185727240-e54323adb7f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2346&q=80',
    },
    small: {
      pl: 'mały',
      port: 'pequeno',
      img: 'https://images.unsplash.com/photo-1633857815556-9951234a2d99?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2068&q=80',
    },
    hot: {
      pl: 'gorący',
      port: 'quente',
      img: 'https://images.unsplash.com/photo-1560977501-7cb367eccebe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1625&q=80',
    },
    cold: {
      pl: 'zimny',
      port: 'frio',
      img: 'https://images.unsplash.com/photo-1577481759281-b2e3a1e62c2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2148&q=80',
    },
    beautiful: {
      pl: 'piękny',
      port: 'bonito',
      img: 'https://images.unsplash.com/photo-1666676173629-0fb328f271a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=830&q=80',
    },
    ugly: {
      pl: 'brzydki',
      port: 'feio',
      img: 'https://images.unsplash.com/photo-1640613074679-182d91956946?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    },
    good: {
      pl: 'dobry',
      port: 'bom',
      img: 'https://images.unsplash.com/photo-1520853504280-249b72dc947c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    },
    bad: {
      pl: 'zły',
      port: 'mau',
      img: 'https://images.unsplash.com/photo-1605270488815-93566ee46a1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2073&q=80',
    },
    rich: {
      pl: 'bogaty',
      port: 'rico',
      img: 'https://images.unsplash.com/photo-1616645004064-aebe96923cbb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1064&q=80',
    },
    poor: {
      pl: 'biedny',
      port: 'pobre',
      img: 'https://images.unsplash.com/photo-1614572864963-045021567dc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1649&q=80',
    },
    old: {
      pl: 'stary',
      port: 'velho',
      img: 'https://images.unsplash.com/photo-1626668011660-051379e9b211?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    young: {
      pl: 'młody',
      port: 'jovem',
      img: 'https://images.unsplash.com/photo-1474925072696-71dd63fdc237?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    new: {
      pl: 'nowy',
      port: 'novo',
      img: 'https://plus.unsplash.com/premium_photo-1663036999053-032355dbd7a5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    // first: { pl: 'pierwszy', port: 'primeiro', img: '' },
    // last: { pl: 'ostatni', port: 'último' , img: ''},
    // money: { pl: 'pieniądze', port: 'dinheiro', img: '' },
    // work: { pl: 'praca', port: 'trabalho' , img: ''},
    // play: { pl: 'grać', port: 'jogar' , img: ''},
    // sunrise: { pl: 'wschód słońca', port: 'nascer do sol', img: '' },
    // sunset: { pl: 'zachód słońca', port: 'pôr do sol', img: '' },
    // morning: { pl: 'ranek', port: 'manhã', img: '' },
    // evening: { pl: 'wieczór', port: 'noite' , img: ''},
    // beach: { pl: 'plaża', port: 'praia' , img: ''},
    // mountain: { pl: 'góra', port: 'montanha', img: '' },
    // river: { pl: 'rzeka', port: 'rio' , img: ''},
    // ocean: { pl: 'ocean', port: 'oceano', img: '' },
    // forest: { pl: 'las', port: 'floresta' , img: ''},
    // rain: { pl: 'deszcz', port: 'chuva', img: '' },
    // snow: { pl: 'śnieg', port: 'neve' , img: ''},
    // summer: { pl: 'lato', port: 'verão' , img: ''},
    // winter: { pl: 'zima', port: 'inverno', img: ''},
    // spring: { pl: 'wiosna', port: 'primavera' , img: ''},
    // autumn: { pl: 'jesień', port: 'outono' , img: ''},
    // red: { pl: 'czerwony', port: 'vermelho', img: '' },
    // blue: { pl: 'niebieski', port: 'azul', img: '' },
    // green: { pl: 'zielony', port: 'verde', img: '' },
    // yellow: { pl: 'żółty', port: 'amarelo' , img: ''},
    // black: { pl: 'czarny', port: 'preto', img: '' },
    // white: { pl: 'biały', port: 'branco', img: '' },
    // orange: { pl: 'pomarańczowy', port: 'laranja' , img: ''},
    // purple: { pl: 'fioletowy', port: 'roxo' , img: ''},
    // laugh: { pl: 'śmiać się', port: 'rir' , img: ''},
    // cry: { pl: 'płakać', port: 'chorar', img: '' },
    // eat: { pl: 'jeść', port: 'comer' , img: ''},
    // drink: { pl: 'pić', port: 'beber', img: '' },
    // sleep: { pl: 'spać', port: 'dormir', img: '' },
    // dream: { pl: 'śnić', port: 'sonhar' , img: ''},
    // run: { pl: 'biec', port: 'correr' , img: ''},
    // walk: { pl: 'chodzić', port: 'andar' },
    // swim: { pl: 'pływać', port: 'nadar' },
    // jump: { pl: 'skakać', port: 'pular' },
    // sing: { pl: 'śpiewać', port: 'cantar' },
    // dance: { pl: 'tańczyć', port: 'dançar' },
    // read: { pl: 'czytać', port: 'ler' },
    // write: { pl: 'pisać', port: 'escrever' },
    // listen: { pl: 'słuchać', port: 'ouvir' },
    // see: { pl: 'widzieć', port: 'ver' },
    // hear: { pl: 'słyszeć', port: 'ouvir' },
    // feel: { pl: 'czuć', port: 'sentir' },
    // think: { pl: 'myśleć', port: 'pensar' },
    // understand: { pl: 'rozumieć', port: 'entender' },
    // speak: { pl: 'mówić', port: 'falar' },
    // learn: { pl: 'uczyć się', port: 'aprender' },
    // teach: { pl: 'uczyć kogoś', port: 'ensinar' },
    // know: { pl: 'wiedzieć', port: 'saber' },
    // yes: { pl: 'tak', port: 'sim' },
    // no: { pl: 'nie', port: 'não' },
    // maybe: { pl: 'może', port: 'talvez' },
    // 'excuse me': { pl: 'przepraszam', port: 'desculpe' },
    // sorry: { pl: 'przepraszam (słowo wyrażające skruchę)', port: 'desculpa' },
    // 'good morning': { pl: 'dzień dobry', port: 'bom dia' },
    // 'good afternoon': { pl: 'dzień dobry (po południu)', port: 'boa tarde' },
    // 'good evening': { pl: 'dobry wieczór', port: 'boa noite' },
    // 'how are you?': { pl: 'jak się masz?', port: 'como está?' },
    // "I'm fine": { pl: 'dobrze się czuję', port: 'estou bem' },
    // 'what?': { pl: 'co?', port: 'o quê?' },
    // 'who?': { pl: 'kto?', port: 'quem?' },
    // 'where?': { pl: 'gdzie?', port: 'onde?' },
    // 'when?': { pl: 'kiedy?', port: 'quando?' },
    // 'why?': { pl: 'dlaczego?', port: 'por que?' },
    // 'how?': { pl: 'jak?', port: 'como?' },
    // 'yes, please': { pl: 'tak, proszę', port: 'sim, por favor' },
    // 'no, thank you': { pl: 'nie, dziękuję', port: 'não, obrigado' },
    // "I don't know": { pl: 'nie wiem', port: 'não sei' },
    // 'I understand': { pl: 'rozumiem', port: 'eu entendo' },
    // "I don't understand": { pl: 'nie rozumiem', port: 'eu não entendo' },
    help: {
      pl: 'pomoc',
      port: 'ajuda',
      img: 'https://plus.unsplash.com/premium_photo-1663100428950-abf1e8f9e80f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2072&q=80',
    },
    // emergency: { pl: 'nagły wypadek', port: 'emergência' },
    // doctor: { pl: 'lekarz', port: 'médico' },
    // hospital: { pl: 'szpital', port: 'hospital' },
    // police: { pl: 'policja', port: 'polícia' },
    // toilet: { pl: 'toaleta', port: 'banheiro' },
    // today: { pl: 'dzisiaj', port: 'hoje' },
    // tomorrow: { pl: 'jutro', port: 'amanhã' },
    // yesterday: { pl: 'wczoraj', port: 'ontem' },
    // week: { pl: 'tydzień', port: 'semana' },
    // month: { pl: 'miesiąc', port: 'mês' },
    // year: { pl: 'rok', port: 'ano' },
    // Monday: { pl: 'poniedziałek', port: 'segunda-feira' },
    // Tuesday: { pl: 'wtorek', port: 'terça-feira' },
    // Wednesday: { pl: 'środa', port: 'quarta-feira' },
    // Thursday: { pl: 'czwartek', port: 'quinta-feira' },
    // Friday: { pl: 'piątek', port: 'sexta-feira' },
    // Saturday: { pl: 'sobota', port: 'sábado' },
    // Sunday: { pl: 'niedziela', port: 'domingo' },
    // home: { pl: 'dom', port: 'casa' },
    // job: { pl: 'praca (zatrudnienie)', port: 'emprego' },
    // buy: { pl: 'kupować', port: 'comprar' },
    // sell: { pl: 'sprzedawać', port: 'vender' },
    // 'wake up': { pl: 'budzić się', port: 'acordar' },
    // go: { pl: 'iść', port: 'ir' },
    // come: { pl: 'przychodzić', port: 'vir' },
    // travel: { pl: 'podróżować', port: 'viajar' },
    // visit: { pl: 'odwiedzać', port: 'visitar' },
    // holiday: { pl: 'wakacje', port: 'férias' },
    // weekend: { pl: 'weekend', port: 'fim de semana' },
    // birthday: { pl: 'urodziny', port: 'aniversário' },
    // gift: { pl: 'prezent', port: 'presente' },
    // bus: { pl: 'autobus', port: 'ônibus' },
    // train: { pl: 'pociąg', port: 'trem' },
    // bicycle: { pl: 'rower', port: 'bicicleta' },
    // plane: { pl: 'samolot', port: 'avião' },
    // ticket: { pl: 'bilet', port: 'bilhete' },
    // cool: { pl: 'fajny', port: 'legal' },
    // awesome: { pl: 'super', port: 'incrível' },
    // crazy: { pl: 'szalony', port: 'louco' },
    // funny: { pl: 'zabawny', port: 'engraçado' },
    // easy: { pl: 'łatwy', port: 'fácil' },
    // difficult: { pl: 'trudny', port: 'difícil' },
    // 'good luck': { pl: 'powodzenia', port: 'boa sorte' },
    // cheers: { pl: 'zdrowie (toast)', port: 'saúde' },
    // "it's okay": { pl: 'wszystko w porządku', port: 'tudo bem' },
    // "what's up?": { pl: 'co tam?', port: 'e aí?' },
    // "I'm hungry": { pl: 'jestem głodny', port: 'estou com fome' },
    // "I'm thirsty": { pl: 'jestem spragniony', port: 'estou com sede' },
    // "I'm tired": { pl: 'jestem zmęczony', port: 'estou cansado' },
    // "I'm bored": { pl: 'jestem znudzony', port: 'estou entediado' },
    // "I don't care": { pl: 'nie obchodzi mnie to', port: 'não me importo' },
    // 'I love you': { pl: 'kocham cię', port: 'eu te amo' },
    // 'I miss you': { pl: 'tęsknię za tobą', port: 'sinto sua falta' },
    // 'leave me alone': { pl: 'zostaw mnie w spokoju', port: 'me deixe em paz' },
    // 'calm down': { pl: 'uspokój się', port: 'acalme-se' },
    // "I'm sorry": { pl: 'przykro mi', port: 'sinto muito' },
    // 'no way': { pl: 'nie ma mowy', port: 'de jeito nenhum' },
    // 'just kidding': { pl: 'żartuję', port: 'estou brincando' },
    // "I don't believe it": { pl: 'nie wierzę', port: 'não acredito' },
    // "that's enough": { pl: 'wystarczy', port: 'chega' },
    // "let's go": { pl: 'chodźmy', port: 'vamos' },
    // 'wait a moment': { pl: 'zaczekaj chwilę', port: 'espere um momento' },
    // 'no problem': { pl: 'nie ma problemu', port: 'sem problema' },
    // 'for sure': { pl: 'na pewno', port: 'com certeza' },
    // "I don't like it": {
    //   pl: 'nie podoba mi się to',
    //   port: 'eu não gosto disso',
    // },
    // 'I like it': { pl: 'podoba mi się to', port: 'eu gosto disso' },
    // amazing: { pl: 'niesamowity', port: 'incrível' },
    // 'no worries': { pl: 'bez obaw', port: 'sem problemas' },
    // 'what a mess': { pl: 'co za bałagan', port: 'que bagunça' },
    // 'my bad': { pl: 'moja wina', port: 'foi mal' },
    // 'keep going': { pl: 'idź dalej', port: 'continue' },
    // 'take care': { pl: 'dbaj o siebie', port: 'cuide-se' },
    // 'stay strong': { pl: 'bądź silny', port: 'mantenha-se forte' },
    // 'enough is enough': { pl: 'dość tego', port: 'chega de ser suficiente' },
    // 'what a shame': { pl: 'jaka szkoda', port: 'que pena' },
    // "you're welcome": { pl: 'proszę (odpowiedź na dziękuję)', port: 'de nada' },
    // "you're crazy": { pl: 'jesteś szalony', port: 'você é louco' },
    // "I don't believe you": {
    //   pl: 'nie wierzę ci',
    //   port: 'não acredito em você',
    // },
    // 'I give up': { pl: 'poddaję się', port: 'eu desisto' },
    // "let's do it": { pl: 'zróbmy to', port: 'vamos fazer isso' },
    // 'count on me': { pl: 'licz na mnie', port: 'conte comigo' },
    // "I'll think about it": {
    //   pl: 'pomyślę nad tym',
    //   port: 'vou pensar sobre isso',
    // },
    // 'never mind': { pl: 'nieważne', port: 'não importa' },
    // "what's going on?": {
    //   pl: 'co się dzieje?',
    //   port: 'o que está acontecendo?',
    // },
    // bathroom: { pl: 'łazienka', port: 'banheiro' },
    // bedroom: { pl: 'sypialnia', port: 'quarto' },
    // 'living room': { pl: 'salon', port: 'sala de estar' },
    // kitchen: { pl: 'kuchnia', port: 'cozinha' },
    // window: { pl: 'okno', port: 'janela' },
    // door: { pl: 'drzwi', port: 'porta' },
    // table: { pl: 'stół', port: 'mesa' },
    // chair: { pl: 'krzesło', port: 'cadeira' },
    // bed: { pl: 'łóżko', port: 'cama' },
    // lamp: { pl: 'lampa', port: 'lâmpada' },
    // phone: { pl: 'telefon', port: 'telefone' },
    // computer: { pl: 'komputer', port: 'computador' },
    // internet: { pl: 'internet', port: 'internet' },
    // newspaper: { pl: 'gazeta', port: 'jornal' },
    // radio: { pl: 'radio', port: 'rádio' },
    // television: { pl: 'telewizja', port: 'televisão' },
    // movie: { pl: 'film', port: 'filme' },
    // music: { pl: 'muzyka', port: 'música' },
    // song: { pl: 'piosenka', port: 'música' },
    // party: { pl: 'impreza', port: 'festa' },
    // anniversary: { pl: 'rocznica', port: 'aniversário' },
    // meeting: { pl: 'spotkanie', port: 'reunião' },
    // appointment: { pl: 'spotkanie (umówione)', port: 'consulta' },
    // watch: { pl: 'zegarek', port: 'relógio' },
    // clock: { pl: 'zegar', port: 'relógio' },
    // hour: { pl: 'godzina', port: 'hora' },
    // minute: { pl: 'minuta', port: 'minuto' },
    // second: { pl: 'sekunda', port: 'segundo' },
    // now: { pl: 'teraz', port: 'agora' },
    // later: { pl: 'później', port: 'mais tarde' },
    // early: { pl: 'wcześnie', port: 'cedo' },
    // chill: { pl: 'zrelaksowany', port: 'de boa' },
    // 'hang out': { pl: 'spotykać się', port: 'sair junto' },
    // 'cool down': { pl: 'ochłonąć', port: 'esfriar a cabeça' },
    // 'go away': { pl: 'odejść', port: 'cair fora' },
    // 'buzz off': { pl: 'odejdź', port: 'some daqui' },
    // 'big deal': { pl: 'duży interes', port: 'grande coisa' },
    // 'piece of cake': { pl: 'bułka z masłem', port: 'moleza' },
    // 'hit the road': { pl: 'wyruszyć', port: 'pegar a estrada' },
    // 'take a hike': { pl: 'zmywać się', port: 'dar o fora' },
    // 'go for it': { pl: 'zrób to', port: 'vai em frente' },
    // 'up to you': { pl: 'to zależy od ciebie', port: 'você que sabe' },
    // 'you bet': { pl: 'jasne, pewnie', port: 'pode apostar' },
    // 'it sucks': { pl: 'to jest do kitu', port: 'é uma droga' },
    // 'keep it up': { pl: 'tak trzymaj', port: 'continue assim' },
    // 'get lost': { pl: 'znikaj', port: 'caia fora' },
    // 'cut it out': { pl: 'przestań', port: 'pare com isso' },
    // 'go with the flow': { pl: 'iść z nurtem', port: 'seguir a correnteza' },
    // 'screw up': { pl: 'schrzanić', port: 'fazer besteira' },
    // 'come on': { pl: 'dawaj', port: 'vamos lá' },
    // 'what a bummer': { pl: 'co za pech', port: 'que chato' },
    // 'keep your cool': { pl: 'zachowaj spokój', port: 'mantenha a calma' },
    // 'out of the blue': { pl: 'nagle, niespodziewanie', port: 'do nada' },
    // 'make up your mind': { pl: 'zdecyduj się', port: 'decida-se' },
    // 'take it easy': { pl: 'spokojnie', port: 'relaxe' },
    // 'get over it': { pl: 'przejmij się tym', port: 'supere isso' },
    // "that's life": { pl: 'takie jest życie', port: 'é a vida' },
    // 'give me a break': { pl: 'daj mi spokój', port: 'me dá um tempo' },
    // 'on the bright side': { pl: 'z drugiej strony', port: 'pensando bem' },
    // 'piece of junk': { pl: 'badziew', port: 'traste' },
    // 'take a look': { pl: 'spójrz', port: 'dê uma olhada' },
    // 'get it': { pl: 'rozumiem', port: 'entendi' },
    // 'got it': { pl: 'kapuję', port: 'peguei' },
    // "that's right": { pl: 'to prawda', port: 'é isso aí' },
    // "can't wait": { pl: 'nie mogę się doczekać', port: 'não vejo a hora' },
    // "it's a deal": { pl: 'umówione', port: 'negócio fechado' },
    // 'you wish': {
    //   pl: 'ciebie to by ucieszyło',
    //   port: 'adoraria que fosse assim',
    // },
    // 'up in the air': { pl: 'niewiadoma', port: 'em aberto' },
    // 'get real': { pl: 'przyjdź do siebie', port: 'caia na real' },
    // "what's the catch": { pl: 'co jest haczykiem', port: 'qual é o truque' },
    // "that's nuts": { pl: 'to szaleństwo', port: 'isso é loucura' },
    // 'get a grip': { pl: 'weź się w garść', port: 'segura a onda' },
    // 'you nailed it': { pl: 'trafiłeś w dziesiątkę', port: 'acertou em cheio' },
    // "it's on me": { pl: 'ja stawiam', port: 'eu pago' },
    // 'give it a shot': { pl: 'spróbuj', port: 'tenta a sorte' },
    // "what's cracking": { pl: 'co tam słychać', port: 'qual é a boa' },
    // 'keep me posted': {
    //   pl: 'informuj mnie na bieżąco',
    //   port: 'me mantenha informado',
    // },
    // "I'm beat": { pl: 'jesteś wykończony', port: 'estou acabado' },
    // 'way to go': { pl: 'brawo, tak trzymaj', port: 'muito bem' },
    // 'watch out': { pl: 'uważaj', port: 'cuidado' },
    // 'take your time': { pl: 'nie spiesz się', port: 'sem pressa' },
    // 'mind your own business': {
    //   pl: 'zajmij się swoim',
    //   port: 'cuide da sua vida',
    // },
    // 'what the heck': { pl: 'co do licha', port: 'que diabos' },
    // 'never again': { pl: 'nigdy więcej', port: 'nunca mais' },
    // 'keep your fingers crossed': {
    //   pl: 'trzymam kciuki',
    //   port: 'torça os dedos',
    // },
    // 'let it go': { pl: 'puść to', port: 'deixa pra lá' },
    // 'give me a hand': { pl: 'pomóż mi', port: 'me dê uma mão' },
    // 'hang on': { pl: 'poczekaj', port: 'segura aí' },
    // 'hold on tight': { pl: 'trzymaj się mocno', port: 'segure-se firme' },
    // "it's not my cup of tea": {
    //   pl: 'to nie moja bajka',
    //   port: 'não é a minha praia',
    // },
    // 'get outta here': { pl: 'wyjdź stąd', port: 'sai daqui' },
    // 'shake it off': { pl: 'odpuść sobie', port: 'sacode a poeira' },
    // 'better late than never': {
    //   pl: 'lepiej późno niż wcale',
    //   port: 'antes tarde do que nunca',
    // },
    // 'bite your tongue': {
    //   pl: 'przytrzymaj język za zębami',
    //   port: 'morde a língua',
    // },
    // 'cry over spilled milk': {
    //   pl: 'nie płacz nad rozlanym mlekiem',
    //   port: 'chorar sobre o leite derramado',
    // },
    // 'the more, the merrier': {
    //   pl: 'im więcej, tym weselej',
    //   port: 'quanto mais, melhor',
    // },
    // "it's a piece of art": {
    //   pl: 'to jest arcydzieło',
    //   port: 'é uma obra de arte',
    // },
    // 'get lost in thought': {
    //   pl: 'zagłębiać się w myślach',
    //   port: 'viajar nos pensamentos',
    // },
    // 'turn a blind eye': {
    //   pl: 'przymknąć na coś oko',
    //   port: 'fazer vista grossa',
    // },
    // 'by all means': { pl: 'za wszelką cenę', port: 'de todo jeito' },
    // "can't stand": { pl: 'nie znosić', port: 'não suportar' },
    // 'piece of work': { pl: 'kawał ciężkiej pracy', port: 'peça de trabalho' },
    // 'have a blast': { pl: 'doskonale się bawić', port: 'se divertir muito' },
    // 'get a move on': { pl: 'dawać nogę', port: 'se apresse' },
    // 'take a wild guess': { pl: 'zgaduj na oko', port: 'dar um palpite' },
    // "it's worth it": { pl: 'warto', port: 'vale a pena' },
    // 'nothing to lose': { pl: 'nic do stracenia', port: 'nada a perder' },
    // 'keep the change': { pl: 'reszty nie trzeba', port: 'fica com o troco' },
    // "it's up to you": { pl: 'to zależy od ciebie', port: 'você decide' },
    // 'let me know': { pl: 'daj mi znać', port: 'me avise' },
    // "it's a long shot": {
    //   pl: 'mała szansa na sukces',
    //   port: 'é difícil, mas pode acontecer',
    // },
    // 'all or nothing': { pl: 'wszystko albo nic', port: 'tudo ou nada' },
    // "what's done is done": {
    //   pl: 'co się stało, to się nie odstanie',
    //   port: 'fechou, acabou',
    // },
    // 'so far, so good': {
    //   pl: 'jak na razie, jest dobrze',
    //   port: 'até agora, tudo bem',
    // },
    // 'keep it down': { pl: 'ścisz się', port: 'fala mais baixo' },
    // 'bottoms up': { pl: 'dół, do dna', port: 'fundo, saúde' },
    // 'give it a rest': { pl: 'odpuść sobie', port: 'descanse' },
    // 'go for broke': { pl: 'wziąć ryzyko', port: 'arriscar tudo' },
    // 'out of this world': { pl: 'niesamowity', port: 'fora desse mundo' },
    // 'up for grabs': { pl: 'do wzięcia', port: 'disponível' },
    // 'not a chance': { pl: 'nie ma szans', port: 'não tem chance' },
    // 'I beg to differ': { pl: 'nie zgadzam się', port: 'discordo' },
    // 'cut the crap': { pl: 'przestań gadać głupoty', port: 'chega de bobagem' },
    // 'watch your back': { pl: 'uważaj na siebie', port: 'cuidado nas costas' },
    // 'the whole nine yards': { pl: 'pełny pakiet', port: 'tudo completo' },
    // 'burn the midnight oil': {
    //   pl: 'pracować do późna w nocy',
    //   port: 'queimar o óleo da meia-noite',
    // },
    // 'speak of the devil': { pl: 'o wilku mowa', port: 'falar do diabo' },
    // 'like father, like son': {
    //   pl: 'jaki ojciec, taki syn',
    //   port: 'filho de peixe, peixinho é',
    // },
    // 'take it or leave it': { pl: 'weź albo zostaw', port: 'pega ou larga' },
    // 'head over heels': {
    //   pl: 'zupełnie zakochany',
    //   port: 'apaixonado de cabeça',
    // },
    // 'bite the bullet': { pl: 'zacisnąć zęby', port: 'engolir o sapo' },
    // 'on the same page': { pl: 'na tej samej stronie', port: 'na mesma página' },
    // 'spill the beans': { pl: 'wypaplać się', port: 'contar tudo' },
    // 'cost an arm and a leg': {
    //   pl: 'kosztować majątek',
    //   port: 'custar os olhos da cara',
    // },
    // 'beat around the bush': { pl: 'owijać w bawełnę', port: 'dar voltas' },
    // 'break a leg': { pl: 'połamania nóg', port: 'quebre uma perna' },
    // 'hit the sack': { pl: 'iść spać', port: 'ir para a cama' },
    // 'take a rain check': { pl: 'odłożyć na później', port: 'dar um desconto' },
    // 'the ball is in your court': {
    //   pl: 'piłka jest po twojej stronie',
    //   port: 'a bola está contigo',
    // },
    // 'a piece of cake': { pl: 'łatwizna', port: 'mamão com açúcar' },
    // "don't cry over spilled milk": {
    //   pl: 'nie płacz nad rozlanym mlekiem',
    //   port: 'chorar sobre o leite derramado',
    // },
    // 'hit the nail on the head': {
    //   pl: 'trafić w sedno',
    //   port: 'acertar na mosca',
    // },
    // 'beat it': { pl: 'znikaj stąd', port: 'cai fora' },
    // 'kick the bucket': { pl: 'kopnąć w kalendarz', port: 'bater as botas' },
    // 'the show must go on': {
    //   pl: 'show musi trwać',
    //   port: 'o espetáculo deve continuar',
    // },
    // 'back to the drawing board': {
    //   pl: 'wracamy do tablicy',
    //   port: 'voltar à estaca zero',
    // },
    // 'speak up': { pl: 'mów głośniej', port: 'fala mais alto' },
    // 'get off my back': {
    //   pl: 'zjedź mi z grzbietu',
    //   port: 'sai de cima de mim',
    // },
    // "let's call it a day": {
    //   pl: 'zakończmy to na dziś',
    //   port: 'vamos encerrar por hoje',
    // },
    // 'take a chill pill': { pl: 'weź pigułkę na wyluzowanie', port: 'relaxa' },
    // 'out of sight, out of mind': {
    //   pl: 'czego oczy nie widzą, tego sercu nie żal',
    //   port: 'o que os olhos não veem, o coração não sente',
    // },
    // "it's a no-brainer": { pl: 'to oczywiste', port: 'é moleza' },
    // 'get your act together': { pl: 'weź się w garść', port: 'se organize' },
    // 'easy does it': { pl: 'powoli, ostrożnie', port: 'devagar e sempre' },
  };
